# This file was generated by GoReleaser. DO NOT EDIT.
cask "urso" do
  name "urso"
  desc "Urso is a GitHub Actions runner manager"
  homepage "https://urso.run"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urso"
  bash_completion "completions/urso.bash"
  zsh_completion "completions/urso.zsh"
  fish_completion "completions/urso.fish"

  on_macos do
    on_intel do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Darwin_x86_64.tar.gz"
      sha256 "f8416792103a378b0cf993c3fc0b9ccbbaf2a512bdff92bd1adf3403063e8753"
    end
    on_arm do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Darwin_arm64.tar.gz"
      sha256 "b5b00ad982fb34a158f6b533e686d6b262434bdfdf5cfac6d2e4c076c572da1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Linux_x86_64.tar.gz"
      sha256 "3e2cdd1bc2a96b01672c0f514f36caea6e8d5293eba1f01d37f9767ded64ebc3"
    end
    on_arm do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Linux_arm64.tar.gz"
      sha256 "10369a8a6de4362d47a1441575ee431e03f8f6d7183626cdf30b327c08a5fe02"
    end
  end

  # No zap stanza required
end
