# This file was generated by GoReleaser. DO NOT EDIT.
cask "urso" do
  name "urso"
  desc "Urso is a GitHub Actions runner manager"
  homepage "https://urso.run"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urso"
  bash_completion "completions/urso.bash"
  zsh_completion "completions/urso.zsh"
  fish_completion "completions/urso.fish"

  on_macos do
    on_intel do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Darwin_x86_64.tar.gz"
      sha256 "d1acf545d9fb049d4811691da7130480cd5b73c187e10b05f7e6456491ee426b"
    end
    on_arm do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Darwin_arm64.tar.gz"
      sha256 "cd7b87d3bbe6d07eb080845d9b6efe3e8293a2383216cbc3c73828a70ec39ad4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Linux_x86_64.tar.gz"
      sha256 "db169de87e7b09c5aa50f5ac06f9603b49cbb8ceac61c145b8041866ef77b504"
    end
    on_arm do
      url "https://github.com/urso-run/urso/releases/download/v#{version}/urso_Linux_arm64.tar.gz"
      sha256 "ab1057fdf4047befe2d8362c58bbb4a800a9d0a8dad49aebcbfca148f832c987"
    end
  end

  # No zap stanza required
end
